import React from "react";
import { useNavigate } from "react-router-dom";
import { ChartBlock } from "../components/runtime/ChartBlock";
import { TableBlock } from "../components/runtime/TableBlock";

const Publication: React.FC = () => {
  const navigate = useNavigate();
  return (
    <div id="page-publication-5">
    <div id="il6ibh" style={{"display": "flex", "height": "100vh", "fontFamily": "Arial, sans-serif", "--chart-color-palette": "default"}}>
      <nav id="iz4k58" style={{"width": "250px", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "padding": "20px", "overflowY": "auto", "display": "flex", "flexDirection": "column", "--chart-color-palette": "default"}}>
        <h2 id="i4ll5d" style={{"marginTop": "0", "fontSize": "24px", "marginBottom": "30px", "fontWeight": "bold", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <a id="i422j5" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "rgba(255,255,255,0.2)", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/publication">{"Publication"}</a>
        <a id="ij7w8k" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/institution">{"Institution"}</a>
        <a id="iu4htl" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/author">{"Author"}</a>
        <div id="insuxv" style={{"display": "flex", "flexDirection": "column", "flex": "1", "--chart-color-palette": "default"}} />
        <p id="izwvs3" style={{"marginTop": "auto", "paddingTop": "20px", "borderTop": "1px solid rgba(255,255,255,0.2)", "fontSize": "11px", "opacity": "0.8", "textAlign": "center", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="iw1uav" style={{"flex": "1", "padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
        <h1 id="irw7ee" style={{"marginTop": "0", "color": "#333", "fontSize": "32px", "marginBottom": "10px", "--chart-color-palette": "default"}}>{"Publication"}</h1>
        <p id="ibh0w6" style={{"color": "#666", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"Manage Publication data"}</p>
        <h2 id="i9klrk">{"Add Publications"}</h2>
        <div id="i9uweu" style={{"maxWidth": "1200px", "margin": "0 auto", "padding": "0 20px", "--chart-color-palette": "default"}}>
          <button id="ivh5s3" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} onClick={() => navigate("/journal")} {...{"type": "button", "data-action-type": "navigate", "data-confirmation": "false", "data-confirmation-message": "Are you sure?", "button-label": "Journal", "data-target-screen": "page-journal-0", "target-screen": "page:page-journal-0"}}>{"Journal"}</button>
          <button id="idp85y" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} onClick={() => navigate("/book")} {...{"type": "button", "data-action-type": "navigate", "data-confirmation": "false", "data-confirmation-message": "Are you sure?", "button-label": "Book", "data-target-screen": "page-book-3", "target-screen": "page:page-book-3"}}>{"Book"}</button>
          <button id="i92wha" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} onClick={() => navigate("/proceedings")} {...{"type": "button", "data-action-type": "navigate", "data-confirmation": "false", "data-confirmation-message": "Are you sure?", "button-label": "Proceedings", "data-target-screen": "page-proceedings-4", "target-screen": "page:page-proceedings-4"}}>{"Proceedings"}</button>
          <button id="iv0hvo" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} onClick={() => navigate("/conference")} {...{"type": "button", "data-action-type": "navigate", "data-confirmation": "false", "data-confirmation-message": "Are you sure?", "button-label": "Conference", "data-target-screen": "page-conference-8", "target-screen": "page:page-conference-8"}}>{"Conference"}</button>
          <button id="i9izve-2" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} onClick={() => navigate("/thesis")} {...{"type": "button", "data-action-type": "navigate", "data-confirmation": "false", "data-confirmation-message": "Are you sure?", "button-label": "Thesis", "data-target-screen": "page-thesis-2", "target-screen": "page:page-thesis-2"}}>{"Thesis"}</button>
          <button id="i9izve" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} onClick={() => navigate("/others")} {...{"type": "button", "data-action-type": "navigate", "data-confirmation": "false", "data-confirmation-message": "Are you sure?", "button-label": "Other", "data-target-screen": "page-others-1", "target-screen": "page:page-others-1"}}>{"Other"}</button>
          <p id="i770pf">{"i770pf"}</p>
        </div>
        <TableBlock id="table-publication-5" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="Publication List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Title", "column_type": "field", "field": "title", "type": "str", "required": true}, {"label": "Author 1", "column_type": "lookup", "path": "author_1", "entity": "Author", "field": "last_name", "type": "list", "required": true}, {"label": "Year", "column_type": "field", "field": "year", "type": "int", "required": true}, {"label": "Institution 1", "column_type": "lookup", "path": "institution_1", "entity": "Institution", "field": "country", "type": "list", "required": true}], "formColumns": [{"column_type": "field", "field": "year", "label": "year", "type": "int", "required": true, "defaultValue": null}, {"column_type": "field", "field": "title", "label": "title", "type": "str", "required": true, "defaultValue": null}, {"column_type": "lookup", "path": "author_1", "field": "author_1", "lookup_field": "name", "entity": "Author", "type": "list", "required": true}, {"column_type": "lookup", "path": "institution_1", "field": "institution_1", "lookup_field": "country", "entity": "Institution", "type": "list", "required": true}]}} dataBinding={{"entity": "Publication", "endpoint": "/publication/"}} />
        <ChartBlock id="iyuv1u" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} chartType="line-chart" title="Number of Publications" color="#4CAF50" chart={{"lineWidth": 2, "curveType": "monotone", "showGrid": true, "showLegend": true, "showTooltip": true, "animate": true, "legendPosition": "top", "gridColor": "#e0e0e0", "dotSize": 5}} series={[{"name": "Series_1", "label": "Series 1", "color": "#4CAF50", "dataSource": "publication", "endpoint": "/publication/", "labelField": "year", "dataField": "year"}]} />
      </main>
    </div>    </div>
  );
};

export default Publication;
